FORMAT: 1A
HOST: https://kiamservice-public.prod.kiam.postag.azureabnprod.postag.intern

# Kiam Public Service


# Group Company

## Companies [/companies]

### CreateCompanyWithBusinessUser [POST]

+ Request (<<Add Header Value>>)
    + Headers

            captchaToken:<<Add Header Value>>


    + Attributes (CreateCompanyRequest)



+ Response 200 

        User was created successfully.




+ Response 400 

        Invalid request.
            
             Usual invalid request response format:
             Error code is validation_error. Information about the error can be found in the details field.
             Target describes which field is invalid, validation error code defines the more detailed validation error case.
             There could be multiple errors per field. See example response.
            
             List of error codes in format [error code] - [optional description] - [fields which can have this validation error] for user fields and company fields:
            
             Company fields
            
             required - company_name
             invalid - company_legal_form_id, company_email_address, company_phone_country_code, company_phone_area_code, company_phone_number, company_mobile_country_code, company_mobile_area_code, company_mobile_number, company_countryIsoAlpha2Code
            
             User fields
             
             required -  Required field. - username, first_name, last_name, registration_origin
             username_not_available - Username is already taken. - username
             too_short - The input value is too short. - username, first_name, last_name
             too_long - The input value is too long. - username, first_name, last_name
             no_titles_allowed - No titles allowed, E.g. BSc. - first_name, last_name
             no_company_types_allowed - No company types allowed. E.g. GmbH. - first_name, last_name
             person_too_young - Person with specified birthdate is too young. - birthdate
             invalid - first_name, last_name, username, phone_country_code, phone_area_code, phone_number, mobile_country_code, mobile_area_code, mobile_number, user_addressX_countryIsoAlpha2Code (where X is the index of the address in the array, starting from 0, e.G. user_address0_countryIsoAlpha2Code)
             new_password_invalid - the new password is invalid - password
             captcha_error - Invalid Captcha token.






# Group DoubleOptIn

## DoubleOptIn Initiate [/doubleOptIn/initiate]

### ResendRegistrationConfirmation [POST]

+ Request (<<Add Header Value>>)

    + Attributes (ResendRegistrationConfirmationRequest)



+ Response 204 

        Registration confirmation e-mail was sent.




+ Response 404 (application/json)

        User with username was not found.

    + Attributes (KiamProblemDetails)



+ Response 409 (application/json)

        An error occurred

    + Attributes (KiamProblemDetails)




## DoubleOptIn Confirm [/doubleOptIn/confirm]

### ConfirmRegistration [POST]

+ Request (<<Add Header Value>>)

    + Attributes (ConfirmRegistrationRequest)



+ Response 202 (application/json)

        Registration confirmation token accepted. Response contains callback URL.

    + Attributes (RegistrationConfirmationResponse)



+ Response 200 (application/json)

        Invalid, expired or already used registration confirmation token.

    + Attributes (KiamProblemDetails)





# Group PublicUser

## Users [/users]

### CreateUser [POST]

+ Request (<<Add Header Value>>)
    + Headers

            captchaToken:<<Add Header Value>>


    + Attributes (CreateUserRequest)



+ Response 200 

        Success






# Group Validations

## Validations ValidateUsername [/validations/validateUsername]

### ValidateUsername [POST]

+ Request (<<Add Header Value>>)

    + Attributes (StringFieldValue)



+ Response 204 

        Value is valid.




+ Response 200 (application/json)

        Value is invalid. Main error code is validation_error.
            Detailed validation error codes can be found in the details field.
            There could be multiple errors.
            
            List of error codes in format [error code] - [description]:
            
            required -  Required field.
            invalid - Invalid format, username should be an email address.
            too_short - The input value is too short.
            too_long - The input value is too long.
            username_not_available - Username is already taken.

    + Attributes (KiamProblemDetails)



+ Response 400 (application/json)
    + Attributes (KiamProblemDetails)




## Validations ValidateDuplicateUser [/validations/validateDuplicateUser]

### ValidateForDuplicateUser [POST]

+ Request (<<Add Header Value>>)

    + Attributes (ValidateForDuplicateUserRequest)



+ Response 204 

        Data is valid, it is not a duplicate user.




+ Response 200 (application/json)

        Data is invalid, a user with the same data already exists. Main error code is validation_error.
            Validation error code is duplicate_user

    + Attributes (KiamProblemDetails)



+ Response 400 (application/json)

        Validation error code is duplicate_user

    + Attributes (KiamProblemDetails)





# Data Structures

## AddressForDuplicateValidation (object)


### Properties
+ `countryIsoAlpha2Code` (string, optional, nullable) 
+ `postalCode` (string, optional, nullable) 
+ `city` (string, optional, nullable) 
+ `street` (string, optional, nullable) 
+ `doorNumber` (string, optional, nullable) 
+ `houseNumber` (string, optional, nullable) 


## ConfirmRegistrationRequest (object)


### Properties
+ `token` (string, optional, nullable) 
+ `applicationName` (string, optional, nullable) 


## CreateAddressRequest (object)


### Properties
+ `addressType` (number, optional, nullable) 
+ `countryIsoAlpha2Code` (string, optional, nullable) 
+ `postalCode` (string, optional, nullable) 
+ `city` (string, optional, nullable) 
+ `street` (string, optional, nullable) 
+ `street2` (string, optional, nullable) 
+ `doorNumber` (string, optional, nullable) 
+ `houseNumber` (string, optional, nullable) 
+ `postAddressCode` (string, optional, nullable) 


## CreateCompanyRequest (object)


### Properties
+ `user` (CreateUserRequest, optional) 
+ `companyName` (string, optional, nullable) 
+ `emailAddress` (string, optional, nullable) 
+ `phone` (Phone2, optional) 
+ `mobile` (Phone2, optional) 
+ `mainAddress` (CreateMainAddressRequest, optional) 
+ `registrationSucceededCallbackUrl` (string, optional, nullable) 
+ `uid` (string, optional, nullable) 
+ `legalFormId` (number, optional, nullable) 
+ `organizationNumber` (string, optional, nullable) 
+ `sapDebitor` (string, optional, nullable) 


## CreateMainAddressRequest (object)


### Properties
+ `countryIsoAlpha2Code` (string, optional, nullable) 
+ `postalCode` (string, optional, nullable) 
+ `city` (string, optional, nullable) 
+ `street` (string, optional, nullable) 
+ `street2` (string, optional, nullable) 
+ `doorNumber` (string, optional, nullable) 
+ `houseNumber` (string, optional, nullable) 
+ `postAddressCode` (string, optional, nullable) 


## CreateUserRequest (object)


### Properties
+ `password` (string, optional, nullable) 
+ `username` (string, optional, nullable) 
+ `salutation` (string, optional, nullable) 
+ `firstname` (string, optional, nullable) 
+ `lastname` (string, optional, nullable) 
+ `birthdate` (string, optional, nullable) 
+ `titleBeforeName` (string, optional, nullable) 
+ `titleAfterName` (string, optional, nullable) 
+ `phone` (Phone2, optional) 
+ `mobile` (Phone2, optional) 
+ `addresses` (array[CreateAddressRequest], optional, nullable) 
+ `registrationSucceededCallbackUrl` (string, optional, nullable) 
+ `registrationOrigin` (string, optional, nullable) 
+ `marketingAgreement` (boolean, optional, nullable) 
+ `newsletter` (boolean, optional, nullable) 


## Phone2 (object)


### Properties
+ `countryCode` (string, optional, nullable) 
+ `areaCode` (string, optional, nullable) 
+ `number` (string, optional, nullable) 


## RegistrationConfirmationResponse (object)


### Properties
+ `callbackUrl` (string, optional, nullable) 


## ResendRegistrationConfirmationRequest (object)


### Properties
+ `username` (string, optional, nullable) 
+ `applicationName` (string, optional, nullable) 


## StringFieldValue (object)


### Properties
+ `value` (string, optional, nullable) 


## ValidateForDuplicateUserRequest (object)


### Properties
+ `firstname` (string, optional, nullable) 
+ `lastname` (string, optional, nullable) 
+ `ssoId` (number, optional, nullable) 
+ `mainAddress` (AddressForDuplicateValidation, optional) 


## KiamProblemDetails (object)


### Properties
+ `type` (string, optional, nullable) 
+ `title` (string, optional, nullable) 
+ `status` (number, optional, nullable) 
+ `detail` (string, optional, nullable) 
+ `instance` (string, optional, nullable) 
+ `error` (Legacy.ErrorInfo, optional) 


## Legacy.ErrorData (object)


### Properties
+ `name` (string, optional, nullable) 
+ `value` (string, optional, nullable) 


## Legacy.ErrorInfo (object)


### Properties
+ `code` (string, optional, nullable) 
+ `message` (string, optional, nullable) 
+ `target` (string, optional, nullable) 
+ `data` (array[Legacy.ErrorData], optional, nullable) 

